#!/usr/bin/env python3
"""
Build the generated internal AI context bundle for Lebensordner.

This bundles AGENTS.md, the mandatory .claude rules, AI collaboration docs,
and the latest changelog entries into one repo-local file that internal prompt
templates can reference consistently.
"""

from __future__ import annotations

from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
OUTPUT = ROOT / "ai" / "context" / "repo-guardrails.md"
CHANGELOG_LINES = 120
SEPARATOR = "\n\n---\n\n"

SOURCE_FILES = [
    "AGENTS.md",
    ".claude/rules/architecture-avoid-boolean-props.md",
    ".claude/rules/architecture-compound-components.md",
    ".claude/rules/patterns-explicit-variants.md",
    ".claude/rules/react-compiler-global-default-hook-discipline.md",
    ".claude/rules/react19-no-forwardref.md",
    ".claude/rules/state-context-interface.md",
    ".claude/rules/state-decouple-implementation.md",
    ".claude/rules/state-lift-state.md",
    "docs/ai-collaboration.md",
    "docs/ai-context.md",
]


def read_text(path: Path) -> str:
    return path.read_text(encoding="utf-8", errors="replace").strip()


def render_section(path: Path) -> str:
    rel = path.relative_to(ROOT).as_posix()
    title = f"## Source: `{rel}`"
    return f"{title}\n\n{read_text(path)}"


def render_changelog_tail(path: Path) -> str:
    lines = path.read_text(encoding="utf-8", errors="replace").splitlines()
    tail = "\n".join(lines[-CHANGELOG_LINES:]).strip()
    return f"## Source: `docs/ai-changelog.md` (latest {CHANGELOG_LINES} lines)\n\n{tail}"


def build_bundle() -> str:
    sections = [
        "# Lebensordner Internal AI Guardrails",
        (
            "This file is generated by `python scripts/ops/build_ai_context.py`.\n\n"
            "It is the canonical context bundle for internal-only AI prompts, evals, "
            "and agent-reference workflows in this repository."
        ),
    ]

    for rel in SOURCE_FILES:
        sections.append(render_section(ROOT / rel))

    sections.append(render_changelog_tail(ROOT / "docs/ai-changelog.md"))
    return SEPARATOR.join(sections) + "\n"


def main() -> int:
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(build_bundle(), encoding="utf-8")
    print(f"Wrote {OUTPUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
