export { VaultSetupIntro } from './intro'
export { VaultSetupPassphrase } from './passphrase'
export { VaultSetupRecoveryKey } from './recovery-key'
export { VaultSetupConfirm } from './confirm'
export { VaultSetupSuccess } from './success'
